export type SheetMasterColumn = {
  key: string;
  label: string;
};

export type SheetMasterFilter = {
  key: string;
  label: string;
  searchable?: boolean;
  optionLabelKeys?: string[];
  optionSearchKeys?: string[];
};

export const PHP_ITEM_MASTER_COLUMNS: SheetMasterColumn[] = [
  { key: "timestamp", label: "Timestamp" },
  { key: "erpItemCode", label: "ERP Item Code" },
  { key: "masterItemNameErpCode", label: "Master Item Name ERP Code" },
  { key: "itemName", label: "Item Name" },
  { key: "company", label: "Company" },
  { key: "openingQty", label: "Opening Qty" },
  { key: "output", label: "Output" },
  { key: "loadedQty", label: "Loaded Qty" },
  { key: "balance", label: "Balance" },
  { key: "rate", label: "Rate" },
  { key: "length", label: "Length" },
  { key: "breadth", label: "Breadth" },
  { key: "height", label: "Height" },
  { key: "creasor1", label: "Creasor 1" },
  { key: "creasor2", label: "Creasor 2" },
  { key: "noOfPly", label: "No. of Ply" },
  { key: "numberOfHolesInPhp", label: "Number of Holes in PHP" },
  { key: "numberOfSetsPerBox", label: "Number of Sets/ Pcs per Box" },
  { key: "fluteType", label: "Flute Type" },
  { key: "takeUp", label: "Take Up" },
  { key: "l1", label: "L1" },
  { key: "l1Bf", label: "L1 BF" },
  { key: "f1", label: "F1" },
  { key: "f1Bf", label: "F1 BF" },
  { key: "l2", label: "L2" },
  { key: "l2Bf", label: "L2 BF" },
  { key: "f2", label: "F2" },
  { key: "f2Bf", label: "F2 BF" },
  { key: "l3", label: "L3" },
  { key: "l3Bf", label: "L3 BF" },
  { key: "boardGsmReq", label: "Board GSM (req) GM/m2" },
  { key: "brustingStrengthReq", label: "Brusting Strength (Req) KG/cm2" },
  { key: "weightPerPcReq", label: "Weight Per Pc/ Set (req)" },
  { key: "calculatedWeightPerPcReq", label: "Calculated Weight Per PC/Set(req)" },
  { key: "category", label: "CATEGORY" },
  { key: "holesOrientationL", label: "Holes Oreintation (L )" },
  { key: "holesOrientationW", label: "Holes Oreintation (W)" },
  { key: "noOfLengthPlates", label: "No. of Length Plates" },
  { key: "noOfWidthPlates", label: "No. of Width Plates" },
  { key: "noOfUpsForRapc", label: "No. of Ups for RAPC" },
  { key: "rapc", label: "RAPC" },
  { key: "noOfUpsForCuttingLengthPiece", label: "No. of Ups for Cutting Length (Length piece)" },
  { key: "cuttingSizeLengthPiece", label: "Cutting Size (Length Piece)" },
  { key: "noOfUpsForCuttingWidthPiece", label: "No. of Ups for Cutting Length (Width Piece)" },
  { key: "cuttingSizeWidthPiece", label: "Cutting Size (Width Piece)" },
  { key: "planQty", label: "Plan Qty" },
  { key: "sheetRequiredLengthPiece", label: "Sheet Required to Produce (Length Piece)" },
  { key: "sheetRequiredWidthPiece", label: "Sheet Required to Produce (Width Piece)" },
  { key: "cutterLocation", label: "Cutter Location" },
  { key: "focOrNonFoc", label: "FOC or non FOC" },
  { key: "nonFocRate", label: "If Non FOC then Rate" },
  { key: "deviation", label: "Deviation" },
  { key: "approvalTimestamp", label: "Approval Timestamp" },
  { key: "approvalEmail", label: "Approval Email" },
  { key: "boxType", label: "BOX TYPE" },
  { key: "syncInItemMaster", label: "SYNC IN ITEM MASTER" },
  { key: "totalWeightGrams", label: "Total Weight (Grams)" },
  { key: "calculatedBGsm", label: "Calculated B GSM" },
  { key: "hostingerSync", label: "Hostinger Sync" },
];

export const PLATE_ITEM_MASTER_COLUMNS: SheetMasterColumn[] = [
  { key: "timestamp", label: "Timestamp" },
  { key: "erpItemCode", label: "ERP Item Code" },
  { key: "masterItemNameErpCode", label: "Master Item Name ERP Code" },
  { key: "itemName", label: "Item Name" },
  { key: "company", label: "Company" },
  { key: "openingQty", label: "Opening Qty" },
  { key: "output", label: "Output" },
  { key: "loadedQty", label: "Loaded Qty" },
  { key: "balance", label: "Balance" },
  { key: "rate", label: "Rate" },
  { key: "typeOfPlate", label: "Type of Plate" },
  { key: "length", label: "Length" },
  { key: "breadth", label: "Breadth" },
  { key: "height", label: "Height" },
  { key: "creasor1", label: "Creasor 1" },
  { key: "creasor2", label: "Creasor 2" },
  { key: "noOfPly", label: "No. of Ply" },
  { key: "numberOfSetsPerBox", label: "Number of Sets/ Pcs per Box" },
  { key: "fluteType", label: "Flute Type" },
  { key: "takeUp", label: "Take Up" },
  { key: "l1", label: "L1" },
  { key: "l1Bf", label: "L1 BF" },
  { key: "f1", label: "F1" },
  { key: "f1Bf", label: "F1 BF" },
  { key: "l2", label: "L2" },
  { key: "l2Bf", label: "L2 BF" },
  { key: "f2", label: "F2" },
  { key: "f2Bf", label: "F2 BF" },
  { key: "l3", label: "L3" },
  { key: "l3Bf", label: "L3 BF" },
  { key: "boardGsmReq", label: "Board GSM (req) GM/m2" },
  { key: "brustingStrengthReq", label: "Brusting Strength (Req) KG/cm2" },
  { key: "weightPerPcReq", label: "Weight Per Pc/ Set (req)" },
  { key: "calculatedWeightPerPcReq", label: "Calculated Weight Per PC/Set(req)" },
  { key: "category", label: "CATEGORY" },
  { key: "noOfUpsForRapc", label: "No. of Ups for RAPC" },
  { key: "rapc", label: "RAPC" },
  { key: "noOfUpsForCutting", label: "No. of Ups for Cutting" },
  { key: "cuttingSizeLengthPiece", label: "Cutting Size (Length Piece)" },
  { key: "planQty", label: "Plan Qty" },
  { key: "sheetRequiredLengthPiece", label: "Sheet Required to Produce (Length Piece)" },
  { key: "cutterLocation", label: "Cutter Location" },
  { key: "focOrNonFoc", label: "FOC or non FOC" },
  { key: "nonFocRate", label: "If Non FOC then Rate" },
  { key: "deviation", label: "Deviation" },
  { key: "approvalTimestamp", label: "Approval Timestamp" },
  { key: "approvalEmail", label: "Approval Email" },
  { key: "boxType", label: "BOX TYPE" },
  { key: "syncInItemMaster", label: "SYNC IN ITEM MASTER" },
  { key: "calculatedBGsm", label: "Calculted B GSM" },
  { key: "totalWeightGrams", label: "Total Weight (Grams)" },
  { key: "hostingerSync", label: "Hostinger Sync" },
];
